In [1]:
pip install pandas numpy matplotlib plotly jupyter

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: plotly in c:\programdata\anaconda3\lib\site-packages (6.3.0)
Requirement already satisfied: jupyter in c:\programdata\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\programdata\anaconda3\lib\site-packages (from plotly) (2.7.0)
Requirement already satisfied: notebook in c:\programdata\anaconda3\lib\site-packages (from jupyter) (7.4.5)
Requirement already satisfied: jupyter-console in c:\programdata\anaconda3\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\programdata\anaconda3\lib\site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipykernel in c:\programdata\anaconda3\lib\site-packages (from jupyter) (6.31.0)
Requirement already satisfied: ipywidgets in c:\programdata\anaconda3\lib\site-packages (from jupyter) (8.1.7)
Requirement already satisfied: jupyterlab in c:\programdata\anaconda3\lib\site-packages (from jupyter) (4.4.7)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (1.8.16)
Requirement already satisfied: ipython>=7.23.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (9.7.0)
Requirement already satisfied: jupyter-client>=8.0.0 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.8.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil>=5.7 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (7.0.0)
Requirement already satisfied: pyzmq>=25 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.2 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (6.5.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.18.1->ipython>=7.23.1->ipykernel->jupyter) (0.8.5)
Requirement already satisfied: platformdirs>=2.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.5.0)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (311)
Requirement already satisfied: executing>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\programdata\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.0)
Requirement already satisfied: pure_eval in c:\programdata\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets->jupyter) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets->jupyter) (3.0.15)
Requirement already satisfied: async-lru>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.0.5)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.16.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (80.9.0)
Requirement already satisfied: anyio in c:\programdata\anaconda3\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.10.0)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\programdata\anaconda3\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.11)
Requirement already satisfied: h11>=0.16 in c:\programdata\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.3.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.3)
Requirement already satisfied: nbformat>=5.3.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: overrides>=5.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.15)
Requirement already satisfied: send2trash>=1.8.2 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jsonschema>=4.18.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (4.25.0)
Requirement already satisfied: requests>=2.31 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.32.5)
Requirement already satisfied: sniffio>=1.1 in c:\programdata\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.28.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.2.1)
Requirement already satisfied: pyyaml>=5.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3339-validator in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\users\divya\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\divya\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\programdata\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\users\divya\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in c:\users\divya\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\divya\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in c:\programdata\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.3.0)
Requirement already satisfied: defusedxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (3.1.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\programdata\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.5.0)
Requirement already satisfied: lark>=1.2.2 in c:\users\divya\appdata\roaming\python\python313\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.0)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.23)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (4.15.0)
Requirement already satisfied: arrow>=0.15.0 in c:\programdata\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.4.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ransformers (C:\Users\divya\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ransformers (C:\Users\divya\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ransformers (C:\Users\divya\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ransformers (C:\Users\divya\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ransformers (C:\Users\divya\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ransformers (C:\Users\divya\AppData\Roaming\Python\Python313\site-packages)

In [2]:
import pandas as pd
import numpy as np

patients = pd.read_csv("patients.csv")
doctors = pd.read_csv("doctors.csv")
appointments = pd.read_csv("appointments.csv")
treatments = pd.read_csv("treatments.csv")
billing = pd.read_csv("billing.csv")

In [3]:
print(patients.head())

  patient_id first_name last_name gender date_of_birth  contact_number  \
0       P001      David  Williams      F    1955-06-04      6939585183
1       P002      Emily     Smith      F    1984-10-12      8228188767
2       P003      Laura     Jones      M    1977-08-21      8397029847
3       P004    Michael   Johnson      F    1981-02-20      9019443432
4       P005      David    Wilson      M    1960-06-23      7734463155

        address registration_date insurance_provider insurance_number  \
0   789 Pine Rd        2022-06-23       WellnessCorp        INS840674
1  321 Maple Dr        2022-01-15        PulseSecure        INS354079
2  321 Maple Dr        2022-02-07        PulseSecure        INS650929
3    123 Elm St        2021-03-02        HealthIndia        INS789944
4    123 Elm St        2021-09-29       MedCare Plus        INS788105

                      email
0   david.williams@mail.com
1      emily.smith@mail.com
2      laura.jones@mail.com
3  michael.johnson@mail.com
4     david.wilson@mail.com

In [4]:
print(doctors.head())

  doctor_id first_name last_name specialization  phone_number  \
0      D001      David    Taylor    Dermatology    8322010158
1      D002       Jane     Davis     Pediatrics    9004382050
2      D003       Jane     Smith     Pediatrics    8737740598
3      D004      David     Jones     Pediatrics    6594221991
4      D005      Sarah    Taylor    Dermatology    9118538547

   years_experience   hospital_branch                         email
0                17   Westside Clinic  dr.david.taylor@hospital.com
1                24   Eastside Clinic    dr.jane.davis@hospital.com
2                19   Eastside Clinic    dr.jane.smith@hospital.com
3                28  Central Hospital   dr.david.jones@hospital.com
4                26  Central Hospital  dr.sarah.taylor@hospital.com

In [5]:
print(appointments.head())

  appointment_id patient_id doctor_id appointment_date appointment_time  \
0           A001       P034      D009       2023-08-09         15:15:00
1           A002       P032      D004       2023-06-09         14:30:00
2           A003       P048      D004       2023-06-28          8:00:00
3           A004       P025      D006       2023-09-01          9:15:00
4           A005       P040      D003       2023-07-06         12:45:00

  reason_for_visit     status
0          Therapy  Scheduled
1          Therapy    No-show
2     Consultation  Cancelled
3     Consultation  Cancelled
4        Emergency    No-show

In [6]:
print(treatments.head())

  treatment_id appointment_id treatment_type         description     cost  \
0         T001           A001   Chemotherapy     Basic screening  3941.97
1         T002           A002            MRI   Advanced protocol  4158.44
2         T003           A003            MRI  Standard procedure  3731.55
3         T004           A004            MRI     Basic screening  4799.86
4         T005           A005            ECG  Standard procedure   582.05

  treatment_date
0     2023-08-09
1     2023-06-09
2     2023-06-28
3     2023-09-01
4     2023-07-06

In [7]:
print(billing.head())

  bill_id patient_id treatment_id   bill_date   amount payment_method  \
0    B001       P034         T001  2023-08-09  3941.97      Insurance
1    B002       P032         T002  2023-06-09  4158.44      Insurance
2    B003       P048         T003  2023-06-28  3731.55      Insurance
3    B004       P025         T004  2023-09-01  4799.86      Insurance
4    B005       P040         T005  2023-07-06   582.05    Credit Card

  payment_status
0        Pending
1           Paid
2           Paid
3         Failed
4        Pending

In [9]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          50 non-null     object
 1   first_name          50 non-null     object
 2   last_name           50 non-null     object
 3   gender              50 non-null     object
 4   date_of_birth       50 non-null     object
 5   contact_number      50 non-null     int64
 6   address             50 non-null     object
 7   registration_date   50 non-null     object
 8   insurance_provider  50 non-null     object
 9   insurance_number    50 non-null     object
 10  email               50 non-null     object
dtypes: int64(1), object(10)
memory usage: 4.4+ KB

In [8]:
doctors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         10 non-null     object
 1   first_name        10 non-null     object
 2   last_name         10 non-null     object
 3   specialization    10 non-null     object
 4   phone_number      10 non-null     int64
 5   years_experience  10 non-null     int64
 6   hospital_branch   10 non-null     object
 7   email             10 non-null     object
dtypes: int64(2), object(6)
memory usage: 772.0+ bytes

In [10]:
appointments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appointment_id    200 non-null    object
 1   patient_id        200 non-null    object
 2   doctor_id         200 non-null    object
 3   appointment_date  200 non-null    object
 4   appointment_time  200 non-null    object
 5   reason_for_visit  200 non-null    object
 6   status            200 non-null    object
dtypes: object(7)
memory usage: 11.1+ KB

In [11]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   treatment_id    200 non-null    object
 1   appointment_id  200 non-null    object
 2   treatment_type  200 non-null    object
 3   description     200 non-null    object
 4   cost            200 non-null    float64
 5   treatment_date  200 non-null    object
dtypes: float64(1), object(5)
memory usage: 9.5+ KB

In [12]:
billing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bill_id         200 non-null    object
 1   patient_id      200 non-null    object
 2   treatment_id    200 non-null    object
 3   bill_date       200 non-null    object
 4   amount          200 non-null    float64
 5   payment_method  200 non-null    object
 6   payment_status  200 non-null    object
dtypes: float64(1), object(6)
memory usage: 11.1+ KB

In [16]:
#check dimension
patients.shape
doctors.shape
appointments.shape
treatments.shape
billing.shape

(200, 7)

In [17]:
patients.duplicated().sum()
doctors.duplicated().sum()
appointments.duplicated().sum()
treatments.duplicated().sum()
billing.duplicated().sum()

np.int64(0)

In [19]:
#convert data  columns
patients["date_of_birth"] = pd.to_datetime(patients["date_of_birth"])

patients["registration_date"] = pd.to_datetime(
    patients["registration_date"])

appointments["appointment_date"] = pd.to_datetime(
    appointments["appointment_date"])

treatments["treatment_date"] = pd.to_datetime(
    treatments["treatment_date"])

billing["bill_date"] = pd.to_datetime(
    billing["bill_date"])

In [25]:
#Standardize text
#columns name
print("Patients")
print(patients.select_dtypes(include='object').columns)

print("\nDoctors")
print(doctors.select_dtypes(include='object').columns)

print("\nAppointments")
print(appointments.select_dtypes(include='object').columns)

print("\nTreatments")
print(treatments.select_dtypes(include='object').columns)

print("\nBilling")
print(billing.select_dtypes(include='object').columns)

Patients
Index(['patient_id', 'first_name', 'last_name', 'gender', 'address',
       'insurance_provider', 'insurance_number', 'email'],
      dtype='object')

Doctors
Index(['doctor_id', 'first_name', 'last_name', 'specialization',
       'hospital_branch', 'email'],
      dtype='object')

Appointments
Index(['appointment_id', 'patient_id', 'doctor_id', 'appointment_time',
       'reason_for_visit', 'status'],
      dtype='object')

Treatments
Index(['treatment_id', 'appointment_id', 'treatment_type', 'description'], dtype='object')

Billing
Index(['bill_id', 'patient_id', 'treatment_id', 'payment_method',
       'payment_status'],
      dtype='object')

In [27]:
#Patients Dataset
# Standardize names
patients["first_name"] = patients["first_name"].str.title().str.strip()
patients["last_name"] = patients["last_name"].str.title().str.strip()

# Standardize gender
patients["gender"] = patients["gender"].str.title().str.strip()

# Standardize address
patients["address"] = patients["address"].str.title().str.strip()

# Standardize insurance provider
patients["insurance_provider"] = patients["insurance_provider"].str.title().str.strip()

# Emails should be lowercase
patients["email"] = patients["email"].str.lower().str.strip()

In [28]:
#Appointments Dataset
# Standardize reason for visit
appointments["reason_for_visit"] = appointments["reason_for_visit"].str.title().str.strip()

# Standardize appointment status
appointments["status"] = appointments["status"].str.title().str.strip()

In [29]:
#Treatments Dataset
# Standardize treatment type
treatments["treatment_type"] = treatments["treatment_type"].str.title().str.strip()

# Standardize description
treatments["description"] = treatments["description"].str.title().str.strip()

In [30]:
#billing dataset
# Standardize payment method
billing["payment_method"] = billing["payment_method"].str.title().str.strip()

# Standardize payment status
billing["payment_status"] = billing["payment_status"].str.title().str.strip()

In [31]:
#checking unique value
print(patients["gender"].unique())
print(doctors["specialization"].unique())
print(appointments["status"].unique())
print(treatments["treatment_type"].unique())
print(billing["payment_status"].unique())

['F' 'M']
['Dermatology' 'Pediatrics' 'Oncology']
['Scheduled' 'No-Show' 'Cancelled' 'Completed']
['Chemotherapy' 'Mri' 'Ecg' 'Physiotherapy' 'X-Ray']
['Pending' 'Paid' 'Failed']

In [32]:
#Data Integration (Merge the Datasets)
patient_appointments = pd.merge(
    patients,
    appointments,
    on="patient_id",
    how="inner"
)

patient_appointments.head()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email,appointment_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,david.williams@mail.com,A007,D007,2023-04-09,10:30:00,Consultation,Scheduled
1,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,david.williams@mail.com,A048,D009,2023-01-16,15:45:00,Emergency,Cancelled
2,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,david.williams@mail.com,A071,D006,2023-01-26,17:00:00,Follow-Up,Scheduled
3,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,david.williams@mail.com,A197,D005,2023-04-01,13:30:00,Emergency,No-Show
4,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,Pulsesecure,INS354079,emily.smith@mail.com,A055,D010,2023-10-06,17:30:00,Checkup,Scheduled

In [33]:
patient_doctor = pd.merge(
    patient_appointments,
    doctors,
    on="doctor_id",
    how="inner"
)

patient_doctor.head()

,patient_id,first_name_x,last_name_x,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,...,appointment_time,reason_for_visit,status,first_name_y,last_name_y,specialization,phone_number,years_experience,hospital_branch,email_y
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,10:30:00,Consultation,Scheduled,Robert,Davis,Oncology,8217493115,26,Westside Clinic,dr.robert.davis@hospital.com
1,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,15:45:00,Emergency,Cancelled,Sarah,Smith,Pediatrics,7387087517,26,Central Hospital,dr.sarah.smith@hospital.com
2,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,17:00:00,Follow-Up,Scheduled,Alex,Davis,Pediatrics,6570137231,23,Central Hospital,dr.alex.davis@hospital.com
3,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,13:30:00,Emergency,No-Show,Sarah,Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com
4,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,Pulsesecure,INS354079,...,17:30:00,Checkup,Scheduled,Linda,Wilson,Oncology,6176383634,21,Eastside Clinic,dr.linda.wilson@hospital.com

In [34]:
patient_treatment = pd.merge(
    patient_doctor,
    treatments,
    on="appointment_id",
    how="inner"
)

patient_treatment.head()

,patient_id,first_name_x,last_name_x,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,...,specialization,phone_number,years_experience,hospital_branch,email_y,treatment_id,treatment_type,description,cost,treatment_date
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,Oncology,8217493115,26,Westside Clinic,dr.robert.davis@hospital.com,T007,Chemotherapy,Advanced Protocol,534.03,2023-04-09
1,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,Pediatrics,7387087517,26,Central Hospital,dr.sarah.smith@hospital.com,T048,Chemotherapy,Advanced Protocol,3249.41,2023-01-16
2,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,Pediatrics,6570137231,23,Central Hospital,dr.alex.davis@hospital.com,T071,Ecg,Advanced Protocol,2960.14,2023-01-26
3,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com,T197,Physiotherapy,Standard Procedure,975.49,2023-04-01
4,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,Pulsesecure,INS354079,...,Oncology,6176383634,21,Eastside Clinic,dr.linda.wilson@hospital.com,T055,Physiotherapy,Basic Screening,1736.63,2023-10-06

In [35]:
healthcare_data = pd.merge(
    patient_treatment,
    billing,
    on=["patient_id", "treatment_id"],
    how="inner"
)

healthcare_data.head()

,patient_id,first_name_x,last_name_x,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,...,treatment_id,treatment_type,description,cost,treatment_date,bill_id,bill_date,amount,payment_method,payment_status
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,T007,Chemotherapy,Advanced Protocol,534.03,2023-04-09,B007,2023-04-09,534.03,Cash,Failed
1,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,T048,Chemotherapy,Advanced Protocol,3249.41,2023-01-16,B048,2023-01-16,3249.41,Credit Card,Failed
2,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,T071,Ecg,Advanced Protocol,2960.14,2023-01-26,B071,2023-01-26,2960.14,Cash,Paid
3,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,T197,Physiotherapy,Standard Procedure,975.49,2023-04-01,B197,2023-04-01,975.49,Cash,Pending
4,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,Pulsesecure,INS354079,...,T055,Physiotherapy,Basic Screening,1736.63,2023-10-06,B055,2023-10-06,1736.63,Cash,Failed

In [36]:
#checking the merged datset
healthcare_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          200 non-null    object
 1   first_name_x        200 non-null    object
 2   last_name_x         200 non-null    object
 3   gender              200 non-null    object
 4   date_of_birth       200 non-null    datetime64[ns]
 5   contact_number      200 non-null    int64
 6   address             200 non-null    object
 7   registration_date   200 non-null    datetime64[ns]
 8   insurance_provider  200 non-null    object
 9   insurance_number    200 non-null    object
 10  email_x             200 non-null    object
 11  appointment_id      200 non-null    object
 12  doctor_id           200 non-null    object
 13  appointment_date    200 non-null    datetime64[ns]
 14  appointment_time    200 non-null    object
 15  reason_for_visit    200 non-null    object
 16  status              200 non-null    object
 17  first_name_y        200 non-null    object
 18  last_name_y         200 non-null    object
 19  specialization      200 non-null    object
 20  phone_number        200 non-null    int64
 21  years_experience    200 non-null    int64
 22  hospital_branch     200 non-null    object
 23  email_y             200 non-null    object
 24  treatment_id        200 non-null    object
 25  treatment_type      200 non-null    object
 26  description         200 non-null    object
 27  cost                200 non-null    float64
 28  treatment_date      200 non-null    datetime64[ns]
 29  bill_id             200 non-null    object
 30  bill_date           200 non-null    datetime64[ns]
 31  amount              200 non-null    float64
 32  payment_method      200 non-null    object
 33  payment_status      200 non-null    object
dtypes: datetime64[ns](5), float64(2), int64(3), object(24)
memory usage: 53.3+ KB

In [37]:
healthcare_data.shape

(200, 34)

In [38]:
healthcare_data.head()

,patient_id,first_name_x,last_name_x,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,...,treatment_id,treatment_type,description,cost,treatment_date,bill_id,bill_date,amount,payment_method,payment_status
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,T007,Chemotherapy,Advanced Protocol,534.03,2023-04-09,B007,2023-04-09,534.03,Cash,Failed
1,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,T048,Chemotherapy,Advanced Protocol,3249.41,2023-01-16,B048,2023-01-16,3249.41,Credit Card,Failed
2,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,T071,Ecg,Advanced Protocol,2960.14,2023-01-26,B071,2023-01-26,2960.14,Cash,Paid
3,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,Wellnesscorp,INS840674,...,T197,Physiotherapy,Standard Procedure,975.49,2023-04-01,B197,2023-04-01,975.49,Cash,Pending
4,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,Pulsesecure,INS354079,...,T055,Physiotherapy,Basic Screening,1736.63,2023-10-06,B055,2023-10-06,1736.63,Cash,Failed

In [40]:
#saving of dataset
healthcare_data.to_csv("healthcare_master.csv",index=False)

In [41]:
#generating KPIs
total_patients = patients["patient_id"].nunique()
print("Total Patients:", total_patients)

Total Patients: 50

In [42]:
total_doctors = doctors["doctor_id"].nunique()
print("Total Doctors:", total_doctors)

Total Doctors: 10

In [43]:
total_appointments = appointments["appointment_id"].nunique()
print("Total Appointments:", total_appointments)

Total Appointments: 200

In [44]:
appointment_status = appointments["status"].value_counts()
print(appointment_status)

status
No-Show      52
Scheduled    51
Cancelled    51
Completed    46
Name: count, dtype: int64

In [45]:
treatment_count = treatments["treatment_type"].value_counts()
print(treatment_count)

treatment_type
Chemotherapy     49
X-Ray            41
Ecg              38
Mri              36
Physiotherapy    36
Name: count, dtype: int64

In [46]:
total_revenue = billing["amount"].sum()
print("Total Revenue:", total_revenue)

Total Revenue: 551249.8500000001

In [47]:
payment_status = billing["payment_status"].value_counts()
print(payment_status)

payment_status
Pending    69
Failed     67
Paid       64
Name: count, dtype: int64

In [48]:
doctor_workload = appointments.groupby("doctor_id").size()
print(doctor_workload)

doctor_id
D001    25
D002    21
D003    22
D004    14
D005    29
D006    24
D007    13
D008    16
D009    17
D010    19
dtype: int64

In [49]:
branch_distribution = doctors["hospital_branch"].value_counts()
print(branch_distribution)

hospital_branch
Central Hospital    4
Westside Clinic     3
Eastside Clinic     3
Name: count, dtype: int64

In [50]:
insurance = patients["insurance_provider"].value_counts()
print(insurance)

insurance_provider
Medcare Plus    18
Wellnesscorp    16
Pulsesecure     10
Healthindia      6
Name: count, dtype: int64

In [52]:
appointments["appointment_date"] = pd.to_datetime(
    appointments["appointment_date"])

appointments["Month"] = appointments["appointment_date"].dt.to_period("M")
monthly_appointments = appointments.groupby("Month").size()
print(monthly_appointments)

Month
2023-01    20
2023-02    14
2023-03    19
2023-04    25
2023-05    19
2023-06    18
2023-07    16
2023-08    15
2023-09    11
2023-10    14
2023-11    17
2023-12    12
Freq: M, dtype: int64

In [53]:
healthcare_data.to_csv("healthcare_master.csv", index=False)
appointment_status.to_csv("appointment_status.csv")
doctor_workload.to_csv("doctor_workload.csv")
treatment_count.to_csv("treatment_summary.csv")
payment_status.to_csv("payment_status.csv")