In [24]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

In [3]:
df = pd.read_csv("medications.csv")

In [4]:
pd.read_csv("medications.csv")

     Medication_ID Admission_ID     Medicine
0           M00001       A00001    Ibuprofen
1           M00002       A00002    Ibuprofen
2           M00003       A00003    Ibuprofen
3           M00004       A00004      Insulin
4           M00005       A00005    Ibuprofen
...            ...          ...          ...
4995        M04996       A04996    Ibuprofen
4996        M04997       A04997  Paracetamol
4997        M04998       A04998  Paracetamol
4998        M04999       A04999    Ibuprofen
4999        M05000       A05000      Insulin

[5000 rows x 3 columns]

In [5]:
df.head()

  Medication_ID Admission_ID   Medicine
0        M00001       A00001  Ibuprofen
1        M00002       A00002  Ibuprofen
2        M00003       A00003  Ibuprofen
3        M00004       A00004    Insulin
4        M00005       A00005  Ibuprofen

In [6]:
df.head(10)

  Medication_ID Admission_ID   Medicine
0        M00001       A00001  Ibuprofen
1        M00002       A00002  Ibuprofen
2        M00003       A00003  Ibuprofen
3        M00004       A00004    Insulin
4        M00005       A00005  Ibuprofen
5        M00006       A00006    Insulin
6        M00007       A00007    Insulin
7        M00008       A00008  Ibuprofen
8        M00009       A00009    Insulin
9        M00010       A00010  Ibuprofen

In [7]:
df.shape

(5000, 3)

In [8]:
df.columns

Index(['Medication_ID', 'Admission_ID', 'Medicine'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Medication_ID  5000 non-null   object
 1   Admission_ID   5000 non-null   object
 2   Medicine       5000 non-null   object
dtypes: object(3)
memory usage: 117.3+ KB

In [11]:
df.describe(include='all')

       Medication_ID Admission_ID   Medicine
count           5000         5000       5000
unique          5000         5000          3
top           M00001       A00001  Ibuprofen
freq               1            1       1692

In [12]:
df.isnull().sum()

Medication_ID    0
Admission_ID     0
Medicine         0
dtype: int64

In [15]:
df.duplicated().sum()
df[df.duplicated()]

Empty DataFrame
Columns: [Medication_ID, Admission_ID, Medicine]
Index: []

In [16]:
pd.read_csv("medications.csv")

     Medication_ID Admission_ID     Medicine
0           M00001       A00001    Ibuprofen
1           M00002       A00002    Ibuprofen
2           M00003       A00003    Ibuprofen
3           M00004       A00004      Insulin
4           M00005       A00005    Ibuprofen
...            ...          ...          ...
4995        M04996       A04996    Ibuprofen
4996        M04997       A04997  Paracetamol
4997        M04998       A04998  Paracetamol
4998        M04999       A04999    Ibuprofen
4999        M05000       A05000      Insulin

[5000 rows x 3 columns]

In [17]:
df["Medicine"] = df["Medicine"].str.strip()

In [18]:
df["Medicine"] = df["Medicine"].str.title()

In [19]:
df["Medicine"].unique()

array(['Ibuprofen', 'Insulin', 'Paracetamol'], dtype=object)

In [20]:
df["Medication_ID"].nunique()

5000

In [21]:
df["Admission_ID"].nunique()

5000

In [26]:
dosage_map = {
    "Paracetamol": ["500 mg", "650 mg"],
    "Ibuprofen": ["200 mg", "400 mg", "600 mg"],
    "Insulin": ["5 Units", "10 Units", "15 Units"]
}

df["Dosage"] = df["Medicine"].apply(lambda x: random.choice(dosage_map[x]))

In [27]:
frequency_map = {
    "Paracetamol": ["Twice Daily", "Three Times Daily"],
    "Ibuprofen": ["Twice Daily", "Three Times Daily"],
    "Insulin": ["Once Daily", "Before Meals"]
}

df["Frequency"] = df["Medicine"].apply(lambda x: random.choice(frequency_map[x]))

In [ ]:
cost_map = {
    "Paracetamol": (10, 30),
    "Ibuprofen": (20, 60),
    "Insulin": (350, 900)
}

df["Cost"] = df["Medicine"].apply(
    lambda x: round(random.uniform(*cost_map[x]), 2)
)

In [29]:
df["Prescribed_By"] = [
    f"D{random.randint(1,350):05d}"
    for _ in range(len(df))
]

In [30]:
start_date = datetime(2024, 1, 1)
end_date = datetime(2025, 12, 31)

df["Sell_Date"] = [
    start_date + timedelta(days=random.randint(0, (end_date - start_date).days))
    for _ in range(len(df))
]

df["Sell_Date"] = df["Sell_Date"].dt.strftime("%Y-%m-%d")

In [31]:
manufacturer_map = {
    "Paracetamol": ["Sun Pharma", "Cipla", "Lupin"],
    "Ibuprofen": ["Dr. Reddy's", "Sun Pharma", "Torrent Pharma"],
    "Insulin": ["Novo Nordisk", "Sanofi", "Eli Lilly"]
}

df["Manufacturer"] = df["Medicine"].apply(
    lambda x: random.choice(manufacturer_map[x])
)

In [32]:
df.head()

,Medication_ID,Admission_ID,Medicine,Dosage,Frequency,Cost,Prescribed_By,Sell_Date,Manufacturer
0,M00001,A00001,Ibuprofen,200 mg,Three Times Daily,59.90,D00238,2024-05-20,Torrent Pharma
1,M00002,A00002,Ibuprofen,400 mg,Twice Daily,44.89,D00261,2024-02-23,Torrent Pharma
2,M00003,A00003,Ibuprofen,200 mg,Twice Daily,24.30,D00220,2025-11-19,Dr. Reddy's
3,M00004,A00004,Insulin,10 Units,Once Daily,644.32,D00208,2024-12-09,Eli Lilly
4,M00005,A00005,Ibuprofen,200 mg,Twice Daily,29.96,D00012,2024-03-07,Torrent Pharma

In [34]:
df.to_csv("medications.csv", index=False)

In [35]:
pd.read_csv("medications.csv")

,Medication_ID,Admission_ID,Medicine,Dosage,Frequency,Cost,Prescribed_By,Sell_Date,Manufacturer
0,M00001,A00001,Ibuprofen,200 mg,Three Times Daily,59.90,D00238,2024-05-20,Torrent Pharma
1,M00002,A00002,Ibuprofen,400 mg,Twice Daily,44.89,D00261,2024-02-23,Torrent Pharma
2,M00003,A00003,Ibuprofen,200 mg,Twice Daily,24.30,D00220,2025-11-19,Dr. Reddy's
3,M00004,A00004,Insulin,10 Units,Once Daily,644.32,D00208,2024-12-09,Eli Lilly
4,M00005,A00005,Ibuprofen,200 mg,Twice Daily,29.96,D00012,2024-03-07,Torrent Pharma
...,...,...,...,...,...,...,...,...,...
4995,M04996,A04996,Ibuprofen,600 mg,Twice Daily,49.72,D00048,2024-02-13,Sun Pharma
4996,M04997,A04997,Paracetamol,500 mg,Twice Daily,15.12,D00026,2025-09-16,Sun Pharma
4997,M04998,A04998,Paracetamol,650 mg,Twice Daily,29.41,D00009,2025-12-03,Sun Pharma
4998,M04999,A04999,Ibuprofen,200 mg,Three Times Daily,58.62,D00167,2024-07-16,Dr. Reddy's
4999,M05000,A05000,Insulin,10 Units,Before Meals,741.38,D00129,2024-01-27,Eli Lilly

In [36]:
df["Medicine"].unique()

array(['Ibuprofen', 'Insulin', 'Paracetamol'], dtype=object)

In [37]:
df.to_csv("medications.csv", index=False)

In [38]:
df.columns

Index(['Medication_ID', 'Admission_ID', 'Medicine', 'Dosage', 'Frequency',
       'Cost', 'Prescribed_By', 'Sell_Date', 'Manufacturer'],
      dtype='object')

In [39]:
df.to_csv("medications.csv", index=False)