In [2]:
import pandas as pd

# Load staff capacity dataset
staff_df = pd.read_csv("../data/raw/staff_capacity.csv")

staff_df.head()

  department_id department_name  Total_Staff
0          D001      Cardiology           55
1          D002       Neurology           40
2          D003     Orthopedics           48
3          D004      Pediatrics           60
4          D005        Oncology           50

In [3]:
#

total_staff = staff_df["Total_Staff"].sum()
average_staff = staff_df["Total_Staff"].mean()
maximum_staff = staff_df["Total_Staff"].max()
minimum_staff = staff_df["Total_Staff"].min()

print("Total Staff:", total_staff)
print("Average Staff per Department:", round(average_staff, 2))
print("Maximum Staff in a Department:", maximum_staff)
print("Minimum Staff in a Department:", minimum_staff)

Total Staff: 767
Average Staff per Department: 38.35
Maximum Staff in a Department: 85
Minimum Staff in a Department: 12

In [4]:
# Highest and Lowest Staff Departments

highest_staff = staff_df.loc[staff_df["Total_Staff"].idxmax()]
lowest_staff = staff_df.loc[staff_df["Total_Staff"].idxmin()]

print("Department with Highest Staff:")
print(highest_staff["department_name"], "-", highest_staff["Total_Staff"])

print("\nDepartment with Lowest Staff:")
print(lowest_staff["department_name"], "-", lowest_staff["Total_Staff"])

Department with Highest Staff:
Emergency - 85

Department with Lowest Staff:
Dental - 12

In [5]:
# Department-wise Staff Ranking

staff_ranking = staff_df.sort_values(
    by="Total_Staff",
    ascending=False
)

print(staff_ranking[["department_name", "Total_Staff"]])

     department_name  Total_Staff
14         Emergency           85
16               ICU           70
3         Pediatrics           60
7    General Surgery           58
0         Cardiology           55
4           Oncology           50
2        Orthopedics           48
10        Gynecology           42
1          Neurology           40
11        Psychiatry           35
9         Nephrology           32
13  Gastroenterology           32
12       Pulmonology           32
8            Urology           28
18     Endocrinology           22
5                ENT           20
17     Ophthalmology           16
15         Radiology           16
6        Dermatology           14
19            Dental           12

In [6]:
# Workforce Efficiency

staff_df["Staff_Share_Percent"] = (
    staff_df["Total_Staff"] / total_staff
) * 100

staff_efficiency = staff_df[
    ["department_name", "Total_Staff", "Staff_Share_Percent"]
].sort_values(
    by="Staff_Share_Percent",
    ascending=False
)

staff_efficiency["Staff_Share_Percent"] = (
    staff_efficiency["Staff_Share_Percent"].round(2)
)

print(staff_efficiency)

     department_name  Total_Staff  Staff_Share_Percent
14         Emergency           85                11.08
16               ICU           70                 9.13
3         Pediatrics           60                 7.82
7    General Surgery           58                 7.56
0         Cardiology           55                 7.17
4           Oncology           50                 6.52
2        Orthopedics           48                 6.26
10        Gynecology           42                 5.48
1          Neurology           40                 5.22
11        Psychiatry           35                 4.56
9         Nephrology           32                 4.17
13  Gastroenterology           32                 4.17
12       Pulmonology           32                 4.17
8            Urology           28                 3.65
18     Endocrinology           22                 2.87
5                ENT           20                 2.61
17     Ophthalmology           16                 2.09
15         Radiology           16                 2.09
6        Dermatology           14                 1.83
19            Dental           12                 1.56

In [7]:
# Patients per Staff

admissions_df = pd.read_csv("../data/raw/admissions.csv")

total_admissions = len(admissions_df)

patients_per_staff = total_admissions / total_staff

print("Total Admissions:", total_admissions)
print("Total Staff:", total_staff)
print("Patients per Staff:", round(patients_per_staff, 2))

Total Admissions: 5000
Total Staff: 767
Patients per Staff: 6.52

In [8]:
# Department-wise Patients per Staff

department_staff = admissions_df.groupby(
    "Department_ID"
).size().reset_index(name="Admissions")

department_staff = department_staff.merge(
    staff_df[["department_id", "department_name", "Total_Staff"]],
    left_on="Department_ID",
    right_on="department_id",
    how="left"
)

department_staff["Patients_per_Staff"] = (
    department_staff["Admissions"] /
    department_staff["Total_Staff"]
)

department_staff["Patients_per_Staff"] = (
    department_staff["Patients_per_Staff"].round(2)
)

department_staff = department_staff.sort_values(
    by="Patients_per_Staff",
    ascending=False
)

print(
    department_staff[
        [
            "Department_ID",
            "department_name",
            "Admissions",
            "Total_Staff",
            "Patients_per_Staff"
        ]
    ]
)

   Department_ID   department_name  Admissions  Total_Staff  \
19          D020            Dental         253           12
17          D018     Ophthalmology         268           16
15          D016         Radiology         266           16
18          D019     Endocrinology         319           22
6           D007       Dermatology         179           14
5           D006               ENT         215           20
12          D013       Pulmonology         317           32
13          D014  Gastroenterology         260           32
11          D012        Psychiatry         253           35
9           D010        Nephrology         218           32
2           D003       Orthopedics         320           48
4           D005          Oncology         331           50
8           D009           Urology         169           28
1           D002         Neurology         200           40
3           D004        Pediatrics         277           60
0           D001        Cardiology         233           55
14          D015         Emergency         335           85
10          D011        Gynecology         159           42
16          D017               ICU         253           70
7           D008   General Surgery         175           58

    Patients_per_Staff
19               21.08
17               16.75
15               16.62
18               14.50
6                12.79
5                10.75
12                9.91
13                8.12
11                7.23
9                 6.81
2                 6.67
4                 6.62
8                 6.04
1                 5.00
3                 4.62
0                 4.24
14                3.94
10                3.79
16                3.61
7                 3.02

In [9]:
# Final Workforce Efficiency Table

workforce_analysis = department_staff[
    [
        "Department_ID",
        "department_name",
        "Admissions",
        "Total_Staff",
        "Patients_per_Staff"
    ]
].copy()

workforce_analysis["Staff_Share_Percent"] = (
    workforce_analysis["Total_Staff"] / total_staff * 100
).round(2)

workforce_analysis = workforce_analysis.sort_values(
    by="Patients_per_Staff",
    ascending=False
)

workforce_analysis

,Department_ID,department_name,Admissions,Total_Staff,Patients_per_Staff,Staff_Share_Percent
19,D020,Dental,253,12,21.08,1.56
17,D018,Ophthalmology,268,16,16.75,2.09
15,D016,Radiology,266,16,16.62,2.09
18,D019,Endocrinology,319,22,14.50,2.87
6,D007,Dermatology,179,14,12.79,1.83
5,D006,ENT,215,20,10.75,2.61
12,D013,Pulmonology,317,32,9.91,4.17
13,D014,Gastroenterology,260,32,8.12,4.17
11,D012,Psychiatry,253,35,7.23,4.56
9,D010,Nephrology,218,32,6.81,4.17
2,D003,Orthopedics,320,48,6.67,6.26
4,D005,Oncology,331,50,6.62,6.52
8,D009,Urology,169,28,6.04,3.65
1,D002,Neurology,200,40,5.00,5.22
3,D004,Pediatrics,277,60,4.62,7.82
0,D001,Cardiology,233,55,4.24,7.17
14,D015,Emergency,335,85,3.94,11.08
10,D011,Gynecology,159,42,3.79,5.48
16,D017,ICU,253,70,3.61,9.13
7,D008,General Surgery,175,58,3.02,7.56

In [10]:
# Identify departments with high staffing pressure

high_pressure = workforce_analysis[
    workforce_analysis["Patients_per_Staff"] >
    workforce_analysis["Patients_per_Staff"].median()
]

high_pressure = high_pressure.sort_values(
    by="Patients_per_Staff",
    ascending=False
)

print("Departments above the median Patients-per-Staff ratio:")
print(
    high_pressure[
        [
            "Department_ID",
            "department_name",
            "Admissions",
            "Total_Staff",
            "Patients_per_Staff"
        ]
    ]
)

Departments above the median Patients-per-Staff ratio:
   Department_ID   department_name  Admissions  Total_Staff  \
19          D020            Dental         253           12
17          D018     Ophthalmology         268           16
15          D016         Radiology         266           16
18          D019     Endocrinology         319           22
6           D007       Dermatology         179           14
5           D006               ENT         215           20
12          D013       Pulmonology         317           32
13          D014  Gastroenterology         260           32
11          D012        Psychiatry         253           35
9           D010        Nephrology         218           32

    Patients_per_Staff
19               21.08
17               16.75
15               16.62
18               14.50
6                12.79
5                10.75
12                9.91
13                8.12
11                7.23
9                 6.81

In [11]:
# Final Workforce & Staffing Efficiency Output

final_workforce = workforce_analysis[
    [
        "Department_ID",
        "department_name",
        "Admissions",
        "Total_Staff",
        "Staff_Share_Percent",
        "Patients_per_Staff"
    ]
].copy()

final_workforce = final_workforce.sort_values(
    by="Patients_per_Staff",
    ascending=False
)

final_workforce

,Department_ID,department_name,Admissions,Total_Staff,Staff_Share_Percent,Patients_per_Staff
19,D020,Dental,253,12,1.56,21.08
17,D018,Ophthalmology,268,16,2.09,16.75
15,D016,Radiology,266,16,2.09,16.62
18,D019,Endocrinology,319,22,2.87,14.50
6,D007,Dermatology,179,14,1.83,12.79
5,D006,ENT,215,20,2.61,10.75
12,D013,Pulmonology,317,32,4.17,9.91
13,D014,Gastroenterology,260,32,4.17,8.12
11,D012,Psychiatry,253,35,4.56,7.23
9,D010,Nephrology,218,32,4.17,6.81
2,D003,Orthopedics,320,48,6.26,6.67
4,D005,Oncology,331,50,6.52,6.62
8,D009,Urology,169,28,3.65,6.04
1,D002,Neurology,200,40,5.22,5.00
3,D004,Pediatrics,277,60,7.82,4.62
0,D001,Cardiology,233,55,7.17,4.24
14,D015,Emergency,335,85,11.08,3.94
10,D011,Gynecology,159,42,5.48,3.79
16,D017,ICU,253,70,9.13,3.61
7,D008,General Surgery,175,58,7.56,3.02

In [12]:
# Save final workforce analysis for visualization

final_workforce.to_csv(
    "../data/processed/workforce_staffing_efficiency.csv",
    index=False
)

print("Workforce staffing analysis saved successfully.")

Workforce staffing analysis saved successfully.